### ISSUE TITLE
Exception thrown when taking issue

### ISSUE THREAD

**Issue by MikaelElkiaer** [deaddog/GitHubConsole#17]
The command:

```
github.exe issues take 16
```

Throws the following exception:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Octokit.NotFoundException: Not Found
   at Octokit.Connection.HandleErrors(IResponse response)
   at Octokit.Connection.<RunRequest>d__18`1.MoveNext()
```

Presumably because I am attempting to self-assign an issue on a repo where I am not a contributor.

**Comment by deaddog** [comment]
@mikaelec - create temp repo with issue so i can test ;)
